spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/cafe
    username: sa
    password: admin
    driverClassName: org.postgresql.Driver

  flyway:
    enabled: true
    user: sa
    password: admin
    schemas: public
    url: jdbc:postgresql://localhost:5437/cafe

data:
  names: src/main/resources/names.txt
  surnames: src/main/resources/surnames.txt
  emails: src/main/resources/emails.txt
  phone_numbers: src/main/resources/phone_numbers.txt
  menu_desserts: src/main/resources/menu_desserts.txt
  menu_drinks: src/main/resources/menu_drinks.txt
  create_tables: src/main/resources/createTables.sql
