DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS receipts;
DROP TABLE IF EXISTS menu;
DROP TABLE IF EXISTS menu_types;
DROP TABLE IF EXISTS schedule;
DROP TABLE IF EXISTS workers;
DROP TABLE IF EXISTS work_positions;
DROP TABLE IF EXISTS clients;
